### PR TITLE
New Templates - not the best - not the worst

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by adam** [comment]
@timmmmyboy now that we have our first submission, how would you like the review process to work?

**Comment by ghost** [comment]
Hi Guys,
If I have a say I would say that I need to include a license on each design and maybe fix the line endings? What do you guys think?

**Comment by timmmmyboy** [comment]
Sorry for the radio silence here. One thing I'm wondering is how folks best integrate only a handful of the templates if the repo has a bunch. I guess they can always just delete the folders they don't want or use their own .gitignore. My initial hesitation with so many themes here is that the majority seem to only change the color which to me seems best done with a configuration setting rather than an entirely different theme. Is there a way we could set up all the color variations to be a dropdown selection for just one theme since they are otherwise almost identical? I know cPanel is working on a file upload option for the future of the Site Publisher project which might help with that part.

**Comment by ghost** [comment]
@timmmmyboy I can remove the duplicate color schema templates. I agree I think it may be best to wait for CPanel to develop the drop down menu or file upload. 

I would also suggest breaking up the themes into independent repositories and then have 1 giant repository that contains them all. It would provide the ability for people to onesy twosy pick themes or they could get them all.

**Comment by adam** [comment]
/me works at cPanel on the team that implemented site publisher

We're going to try to have image upload support for v60 (slated for the next release in the fall timeframe) but I can't say the same about dropdown support.  We're eyeing our implementation of the form-builder and want to iterate on it a good deal (potentially even switch JS libraries) in order to add support for dropdowns, checkboxes, radio buttons and other form elements we don't currently support.

**Comment by adam** [comment]
As far as license files go, that's a good idea. A 'best practice' even!

**Comment by ghost** [comment]
@adam I'm more than willing to add the MIT license to all of our templates. Your very right it should be considered a best practice.

**Comment by timmmmyboy** [comment]
Yeah I agree on the addition of licensing, since folks would be adding these to public-facing sites and hosts would potentially be including them for reuse with that purpose in mind it's important. I also like the idea of a "repository of repositories" but I'm unclear technically on what that might look like. My gut says perhaps [submodules](https://github.com/blog/2104-working-with-submodules), it just makes things a bit trickier because you have to add flags when cloning to get them and they're not included in any bundled downloads from GitHub so it can cause confusion. @adam thanks for chiming in on the timeline for developments with Site Publisher, I knew some of that stuff was in the works but wasn't sure when to expect it. I think the additional flexibility of the tool will be a welcome enhancement!

**Comment by adam** [comment]
@waknauss-kingdom - As a thought, you may want to include version numbers or whatever author  info you'd like to include in the meta.json for your templates.  Site Publisher will disregard any key => value pairs in the information element that it doesn't expect, so that's the place to put this.

**Comment by adam** [comment]
...that comment re meta info is certainly not required, though.  @timmmmyboy I officially give this pull request a (thumbsup) and recommend it's acceptance when we're ready to do that!

**Comment by ghost** [comment]
@kstry-kingdom - want to add version numbers to the meta data?

**Pull request merged**
